# Generated by Django 3.0.3 on 2020-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_DG', models.CharField(max_length=10)),
                ('ten_DG', models.CharField(max_length=100)),
                ('gioitinh', models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam')], default=0)),
                ('email_DG', models.EmailField(max_length=200)),
                ('CMND', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
