# Generated by Django 3.0.3 on 2020-02-17 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_docgia_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgia',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 6, 49, 158925)),
        ),
    ]
