# Generated by Django 3.0.3 on 2020-02-17 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200217_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docgia',
            name='id',
        ),
        migrations.AlterField(
            model_name='docgia',
            name='id_DG',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 11, 5, 480934)),
        ),
    ]
