# Generated by Django 3.0.3 on 2020-02-17 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200217_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgia',
            name='id_DG',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 22, 23, 4, 501605)),
        ),
    ]
