# Generated by Django 3.0.3 on 2020-03-10 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200304_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.CharField(default='75360001', max_length=10),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 20, 58, 40, 976123)),
        ),
    ]
