# Generated by Django 3.0.3 on 2020-03-10 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200310_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 21, 2, 50, 276664)),
        ),
    ]
