# Generated by Django 3.0.3 on 2020-03-10 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200310_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='id_book',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 21, 14, 49, 709527)),
        ),
    ]
