# Generated by Django 3.0.3 on 2020-03-10 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200310_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(upload_to='login/static/image_book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 22, 49, 2, 675913)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 22, 49, 2, 674914)),
        ),
    ]
