# Generated by Django 3.0.3 on 2020-03-10 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20200310_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='login/static/image_book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 23, 11, 41, 966580)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 23, 11, 41, 965583)),
        ),
    ]
