# Generated by Django 3.0.3 on 2020-03-10 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200311_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 0, 56, 34, 784793)),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
