# Generated by Django 3.0.3 on 2020-03-10 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20200311_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 0, 57, 28, 996817)),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('image_book', models.ImageField(blank=True, null=True, upload_to='image_book/')),
                ('active', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2020, 3, 11, 0, 57, 28, 996817))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Category_Book')),
            ],
        ),
    ]
