# Generated by Django 3.0.3 on 2020-03-13 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20200313_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='docgia',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='login.DocGia'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 21, 29, 34, 754604)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 21, 29, 34, 752609)),
        ),
    ]
