# Generated by Django 3.0.3 on 2020-03-13 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20200313_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='docgia',
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 21, 49, 53, 251611)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 21, 49, 53, 252608)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 21, 49, 53, 251611)),
        ),
    ]
