# Generated by Django 3.0.3 on 2020-03-20 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20200314_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id_bor',
            new_name='id_bor1',
        ),
        migrations.AddField(
            model_name='cart',
            name='id_bor2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='id_bor3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 22, 42, 12, 575386)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 22, 42, 12, 576382)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 22, 42, 12, 574427)),
        ),
    ]
