# Generated by Django 3.0.3 on 2020-03-21 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20200321_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgia',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 20, 59, 49, 740181)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 20, 59, 49, 787013, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 20, 59, 49, 740181)),
        ),
    ]
