# Generated by Django 3.0.3 on 2020-03-21 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_auto_20200321_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docgia',
            name='money',
        ),
        migrations.AddField(
            model_name='docgia',
            name='money_user',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 21, 7, 26, 518332)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 21, 7, 26, 580811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 21, 7, 26, 518332)),
        ),
    ]
