# Generated by Django 3.0.3 on 2020-03-21 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0048_auto_20200321_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocGia',
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 21, 13, 43, 294571)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 21, 13, 43, 419572, tzinfo=utc)),
        ),
    ]
