# Generated by Django 3.0.3 on 2020-03-24 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0053_auto_20200321_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bor', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 22, 59, 37, 632315)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 22, 59, 40, 290103, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 22, 59, 37, 631325)),
        ),
    ]
