# Generated by Django 3.0.3 on 2020-03-28 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0054_auto_20200324_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 14, 58, 51, 337034)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 14, 58, 51, 450760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 14, 58, 51, 336036)),
        ),
    ]
