# Generated by Django 3.0.3 on 2020-04-03 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0055_auto_20200328_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('opinion', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 17, 49, 46, 113418)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 17, 49, 46, 176291, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_user',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='docgia',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 17, 49, 46, 99455)),
        ),
    ]
