# Generated by Django 3.0.3 on 2020-04-04 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0057_auto_20200404_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='docgia',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='image_user/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 58, 42, 193026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 58, 42, 193026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 58, 42, 193026, tzinfo=utc)),
        ),
    ]
