# Generated by Django 3.0.3 on 2020-04-10 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0060_auto_20200404_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='vote',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create1',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 22, 33, 43, 98764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create2',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 22, 33, 43, 99763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='create3',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 22, 33, 43, 99763, tzinfo=utc)),
        ),
    ]
